bayes_people_tracker:
    filter_type: "EKF"                                         # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
    cv_noise_params:                                           # The noise for the constant velocity prediction model
        x: 0.1
        y: 0.1
    detectors:                                                 # Add detectors under this namespace
        blob_detector:                                   # Name of detector (used internally to identify them). Has to be unique.
            topic: "/velodyne_detections" # The topic on which the geometry_msgs/PoseArray is published
            cartesian_noise_params:                            # The noise for the cartesian observation model
                x: 1.0
                y: 1.0
            matching_algorithm: "NN"                       # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
